import './setup'
export * from './Chart.js'
export * from './ChartBar.js'
export * from './ChartLine.js'
export * from './ChartScatter.js'
export * from './ChartBubble.js'
export * from './ChartPie.js'
export * from './ChartDoughnut.js'
export * from './ChartPolarArea.js'
export * from './ChartRadar.js'