import './setup'
export * from './Chart.js'
export * from './ChartBar'
export * from './ChartLine'
export * from './ChartScatter'
export * from './ChartBubble'
export * from './ChartPie'
export * from './ChartDoughnut'
export * from './ChartPolarArea'
export * from './ChartRadar'